import "./globals.css"
import { Metadata } from "next/dist/lib/metadata/types/metadata-interface"
import Layout from "@/components/layout/layout"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <Layout>{children}</Layout>
        </body>
      </html>
    </>
  )
}
